# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cumulative sum of uninterrupted '1'
#' 
#' 
#' @param x integer vector to be used
#' 
#' @return integer vector 
#' 
#' @details 
#' Returns a vector whose elements are the 
#' cumulative sums of uninterrupted entries equal to 1 in an integer vector
#' 
#' @examples 
#'  \dontrun{
#' 
#'  x <- c(0,1,1,1,0,0,1,1,1,0,0)
#' 
#'  cumsum1(x)
#' 
#'  } 
#' 
#' 
#' 
#' @export
cumsum1 <- function(x) {
    .Call('_datatools_cumsum1', PACKAGE = 'datatools', x)
}

#' Creates a unique ID for all uninterrupted series 
#'
#' 
#' @param x numeric vector to be used
#' 
#' @return an integer vector 
#' 
#' @details
#' Creates a unique, numeric ID for each uninterrupted sequence of equal values in a vector 
#' 
#' @examples 
#'  \dontrun{
#' 
#'  x <- c(0,1,1,1,2,2,1,3,1,0,0)
#' 
#'  make_series_id(x)
#' 
#'  } 
#' 
#' 
#' 
#' @export
make_series_id <- function(x) {
    .Call('_datatools_make_series_id', PACKAGE = 'datatools', x)
}

